### ISSUE TITLE
aspace2alma stops prematurely

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#322]
**Describe the bug**
The MARC_out.xml output file ends abruptly, without closing 

**Steps to replicate**
Run get_MARCxml.rb locally. The behavior is erratic--sometimes it ends prematurely, sometimes it finishes fine.

**Expected behavior**
The file should run through all the resource records, process them, end then close out with the `</collection>` tag.

### Impact of this bug
Updates don't make it to Alma

**Comment by regineheberlein** [comment]
Observed for the first time yesterday and fixed some suspected culprits; happened again overnight. I manually put a complete file on the server and will import it to Alma this morning to get the updates into the catalog while we continue to investigate.

**Comment by regineheberlein** [comment]
It happened again overnight on lib-jobs. The last record that succeeded last night was AC138 in repo 3. The day before, the process stopped somewhere in repo 5, i.e. advanced farther before it stopped. This suggests a connection or network outage rather than a data error.

I checked with Lyrasis about outages, but they're seeing nothing in their server and API logs. 

Manual re-run succeeds again this morning.

I'm wondering whether this could be something on lib-jobs?

**Comment by regineheberlein** [comment]
Stopped prematurely again last night; the last record processed was C1115 in repo 5.

**Comment by regineheberlein** [comment]
Stopped at C1583. The log file was not created.

**Comment by regineheberlein** [comment]
Stopped at `Fetched record C0193 at 2023-01-19 09:14:11 +0000` (stdout)  with error
```
/usr/local/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1530:in `request'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty/request.rb:152:in `perform'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:527:in `get'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/request.rb:40:in $
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/client.rb:62:in `$
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/client.rb:22:in `$
        from get_MARCxml.rb:48:in `block in fetch_and_process_records'
        from get_MARCxml.rb:46:in `each'
        from get_MARCxml.rb:46:in `fetch_and_process_records'
        from get_MARCxml.rb:205:in `<main>'
```

**Comment by regineheberlein** [comment]
Stopped at `Fetched record C1065 at 2023-01-20 09:10:25 +0000` with error 

```
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to aspace.princeton.edu:443 (Connecti$
        from /usr/local/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
        from /usr/local/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
        from /usr/local/lib/ruby/3.1.0/socket.rb:137:in `connect'
        from /usr/local/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `each'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/local/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:998:in `connect'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1614:in `begin_transport'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1565:in `transport_request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1539:in `request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1532:in `block in request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:966:in `start'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1530:in `request'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty/request.rb:152:in `perform'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:527:in `get'
from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/request.rb:40:in $
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/client.rb:62:in `$
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/client.rb:22:in `$
        from get_MARCxml.rb:48:in `block in fetch_and_process_records'
        from get_MARCxml.rb:46:in `each'
        from get_MARCxml.rb:46:in `fetch_and_process_records'
        from get_MARCxml.rb:205:in `<main>'
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 44.224.179.199:443 (Errno::ECON$
        from /usr/local/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
        from /usr/local/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
        from /usr/local/lib/ruby/3.1.0/socket.rb:137:in `connect'
from /usr/local/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `each'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/local/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:998:in `connect'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1614:in `begin_transport'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1565:in `transport_request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1539:in `request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1532:in `block in request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:966:in `start'
 from /usr/local/lib/ruby/3.1.0/net/http.rb:1530:in `request'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty/request.rb:152:in `perform'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:527:in `get'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/request.rb:40:in $
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/client.rb:62:in `$
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/archivesspace-client-0.1.11/lib/archivesspace/client/client.rb:22:in `$
        from get_MARCxml.rb:48:in `block in fetch_and_process_records'
        from get_MARCxml.rb:46:in `each'
        from get_MARCxml.rb:46:in `fetch_and_process_records'
        from get_MARCxml.rb:205:in `<main>'
```

**Comment by regineheberlein** [comment]
And this is what I get for that IP:

`lib-macheberlein:aspace2alma heberleinr$ nslookup 44.224.179.199
Server:		128.112.128.50
Address:	128.112.128.50#53

Non-authoritative answer:
199.179.224.44.in-addr.arpa	name = ec2-44-224-179-199.us-west-2.compute.amazonaws.com`

**Comment by regineheberlein** [comment]
We're hitting the rate limit, per Blake at Lyrasis--NB "34" below should read "3-4":

> Yep, I see it from yesterday. Looks like you're hitting the rate limit. I'm seeing 34 hits a second, which is not super fast, but fast enough to trip the rate limits. 
>  
> This brings up something we haven't thought about before, the API/Staff should have a much higher limit that the PUI. It's never been a problem before, right now API/Staff and PUI all have the same limit.
> Let me see what I can do on that, I'd like to break those apart, but I'm not sure how to do that with our current set up.
