### ISSUE TITLE
aspace2alma stopped sending records to libsftp

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#398]
**Describe the bug**
MARC_out.xml on lib-sftp-prod1 was last updated on May 24.

**Expected behavior**
The file should update daily.

### Impact of this bug
Records in Alma are stale.

Sudden priority justification: Users are seeing outdated records in Blacklight.

**Comment by regineheberlein** [comment]
Yikes, I don't think we ever updated https://github.com/pulibrary/aspace_helpers/blob/main/reports/aspace2alma/get_MARCxml.rb#13-15 to reflect the changes to lib-sftp

**Comment by regineheberlein** [comment]
@maxkadel got this to work on staging, but running it manually on prod, it's still hanging. The MARC creation finishes, but the process then hangs at the sftp step.

```
deploy@lib-jobs-prod1:/opt/aspace_helpers/current/reports/aspace2alma$ tail -f log_err.txt
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:227:in `process'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `block in loop'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-sftp-3.0.0/lib/net/sftp/session.rb:804:in `loop'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-sftp-3.0.0/lib/net/sftp/session.rb:789:in `connect!'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-sftp-3.0.0/lib/net/sftp.rb:40:in `start'
	from get_MARCxml.rb:14:in `alma_sftp'
	from get_MARCxml.rb:57:in `fetch_and_process_records'
	from get_MARCxml.rb:240:in `<main>'
```

**Comment by regineheberlein** [comment]
sftp from lib-jobs-prod1 succeeds manually. Dedeployed aspace_helpers.

**Comment by regineheberlein** [comment]
Redeploy didn't fix it
