### ISSUE TITLE
Alma seems to be importing stale ASpace export files

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#438]
This surfaced because @jmeyer4 noticed deleted holdings come back into archival Alma records. Check the following:
- [x] server on which aspace2alma runs: `lib-jobs-prod2`
- [x] datestamp of file on lib-jobs-prod2: `-rw-rw-r-- 1 deploy deploy 15479320 Sep 29 10:13 MARC_out.xml`
- [x] ftp server it sends to: `lib-sftp-prod1`
- [x] datestamp of file on lib-sftp-prod1: `-rw-r--r-- 1 almasftp                            domain users@pu.win.princeton.edu 15472272 Sep 22 16:39 MARC_out.xml`
- [ ] ftp server Alma import profile pulls from:

Sudden priority: Alma is not updating from ASpace; this is also impeding the ReCAP project.

**Comment by regineheberlein** [comment]
Issue: 
- the last time the file ran on lib-jobs is 9/29
- the last time the file was saved to lib-sftp is 9/22
- the error log is blank

**Comment by regineheberlein** [comment]
After upgrading net-sftp to v4 on lib-jobs-staging2, it still gives
```
/opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError)
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key'
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:32:in `initialize' 
        from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `new'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `exchange_keys'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:245:in `proceed!'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:184:in `accept_kexinit'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `loop'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `wait'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:90:in `initialize'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
	from /opt/aspace_helpers/shared/bundle/ruby/3.1.0/gems/net-sftp-4.0.0/lib/net/sftp.rb:36:in `start'
	... 20 levels...
```
