### ISSUE TITLE
Test the marcao plugin with v3.5

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#546]
We are testing v3.5 on staging before upgrading our prod instance. In order to make sure the upgrade won't break anything, we need to test all the plugins, in particular the marcao plugin, which connects to lib-sftp. 

(This will (hopefully) also confirm that the new infrastructure doesn't add complexity.)

We need to configure the plugin to send files to libsftp-staging, and we need to configure libsftp-staging to accept files from aspace-staging:
- [x] allow aspace-staging (44.225.143.31) to connect to libsftp-staging (not prod)
- [ ] configure plugin to send to libsftp-staging: host, user, pw

## Acceptance criteria
- [ ] aspace-staging successfully connects to libsftp-staging

**Comment by regineheberlein** [comment]
@acozine @kayiwa 

The as_marcao plugin still can't connect from our hosted aspace staging server to lib-sftp-staging1. Here is what I got from Blake. It sounds like the issue is the Amazon server. Any ideas?

> I do see some fails in the logs today now that we have the right stuff in place:
 
```
W, [2024-05-16T22:24:46.181826 #513]  WARN -- : Thread-3940: marcao: Upload to SFTP failed: Connect timed out
W, [2024-05-16T22:24:46.182212 #513]  WARN -- : Thread-3940: marcao: Will retry 9 more times
 
```
>and so on until....
 
```
W, [2024-05-16T22:47:17.056056 #513]  WARN -- : Thread-3940: marcao: Upload to SFTP failed: Connect timed out
E, [2024-05-16T22:47:17.056388 #513] ERROR -- : Thread-3940: marcao: SFTP upload has failed 10 times.  Giving up!
================================================================================
scheduler caught exception:
undefined method `[]' for nil:NilClass
/archivesspace/plugins/as_marcao/backend/model/marc_ao_exporter.rb:80:in `run'
/archivesspace/plugins/as_marcao/backend/plugin_init.rb:30:in `block in <main>'
/archivesspace/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/archivesspace/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/archivesspace/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
 
```

> I tried to ssh/sftp from the instance and it times out. I did curl checkip.amazonaws.com from there and it gives me the IP  44.225.143.31  so I think that first one we gave you was correct. It looks like we can't connect from here to there.

**Comment by regineheberlein** [comment]
The same thing happens when aspace-staging tries to connect to lib-sftp-prod1, which might mean it's a firewall thing?
